# Generated by Django 6.0.7 on 2026-07-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_skill_kind_orchestrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='entry_point',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='output_type',
            field=models.CharField(blank=True, default='html', max_length=50),
        ),
    ]
